apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    app: wordpress
    tier: mysql
  namespace: wordpress
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: manual
  hostPath:
    path: /home/boris/git-repos/wordpress_project/volumes/mysql_storage
