apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  labels:
    app: wordpress
  namespace: wordpress
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
